"""fix bags; add language to posts

Revision ID: 084d9acf7039
Revises: 509e67f1144b
Create Date: 2018-12-12 01:56:53.394961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084d9acf7039'
down_revision = '509e67f1144b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
