"""add new field to User: 'about_me' and 'last_seen'

Revision ID: 45567a29e932
Revises: e692357150dd
Create Date: 2018-04-29 23:29:00.927135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45567a29e932'
down_revision = 'e692357150dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=240), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
